### ISSUE TITLE
Publish the first version

### ISSUE THREAD

**Issue by mazgi** [mazgi/http-ok-whatever#1]
## Todo

- [x] Set up the repo and project
- [ ] Write out basic article to STDOUT
- [ ] Write out tar archive via HTTP
- [ ] Generate fake article using https://github.com/go-faker/faker
